### ISSUE TITLE
Antenna to extend range?

### ISSUE THREAD

**Issue by Brandon4466** [ChristopheJacquet/PiFmRds#101]
Are there any suggestions for an antenna to use with this? Others experiences?

I have found anything like this: https://www.amazon.com/dp/B01HTDKAWS/ref=cm_sw_r_cp_apa_JsbxAbGW04SRV

Would something like this work? Does anyone know how you would connect something like this best to the GPIO?

Basically just the best way to boost the radius. Any suggestions would be great! What do you guys use for an antenna?

Thanks!

**Comment by hex007** [comment]
There are various restrictions in place for FM broadcasting based on your country. Please check them before broadcasting with higher power antennas.

https://github.com/ChristopheJacquet/PiFmRds#warning-and-disclaimer

**Comment by Artoria2e5** [comment]
Assuming you know what you are doing, there's always https://ham.stackexchange.com/7365 …

**Comment by MinePro120** [comment]
A 30cm copper wire with a female jumper cable mounted on the one side should do the trick. That's what I use.
