### ISSUE TITLE
Actually transmitting a TA announcement

### ISSUE THREAD

**Issue by JsBergbau** [ChristopheJacquet/PiFmRds#105]
Switching TA on causes the Radio to show the sender is capable of transmitting Traffic announcements. However it does not show an ongoing announcement like "real" stations. How is it done that Radio shows an ongoing announcement? I've already tried playing a Hinz Triller, but nothing happend (except hearing this enerving tone :) )

**Comment by ChristopheJacquet** [comment]
As far as I can tell, Pi-FM-RDS works fine. I just checked this again with a Sony receiver. I'd assume something is wrong with your receiver, or maybe with the way it is set up.

RDS uses two flags:
- TP indicates that the sender is capable of sending traffic announcements. Pi-FM-RDS always sets it.
- TA indicates that a traffic announcement is currently playing. In Pi-FM-RDS, you can toggle it via the control pipe.

On the Hinz Triller: it has no impact on _receivers_, and it never had. This tune had a function in the days of the ARI system (the precursor of RDS): it was a way to tell the _transmitter_ to set ARI's equivalent of the TA flag by using in-band signaling from the studio. Now that ARI is long gone, it is not used anymore for technical purposes, but merely as a jingle to signal traffic information to _listeners_ as it has become part of the culture in German-speaking countries. See https://de.wikipedia.org/wiki/Autofahrer-Rundfunk-Information#Hinz-Triller
