### ISSUE TITLE
RDS Not Working On Ford Focus Sync System

### ISSUE THREAD

**Issue by JonQuan2** [ChristopheJacquet/PiFmRds#108]
With the Ford Focus Sync System I only get the program name and not the radio text. Is it the encoding because it works fine on other RDS devices

**Comment by ChristopheJacquet** [comment]
Does the Ford Focus receiver display some RT from commercial stations?

**Comment by ChristopheJacquet** [comment]
Closing after 1+ year of inactivity, and likely not Pi-FM-RDS-related.
