### ISSUE TITLE
Bluetooth option??

### ISSUE THREAD

**Issue by ikoydg** [ChristopheJacquet/PiFmRds#111]
is there a way to get the songs from a phone via bluetooth?

like phone (playing music) -> bluetooth to rpi 3 -> then pifmrds transmit it? 
thanks!

**Comment by ChristopheJacquet** [comment]
It's probably possible... but well beyond the cope of Pi-FM-RDS! Pi-FM-RDS is an experimental tool that focuses on one task: transmit FM/RDS with audio. If you can pipe audio from Bluetooth to Pi-FM-RDS, then it will work.
