### ISSUE TITLE
Radio transmission will stop after a while 

### ISSUE THREAD

**Issue by jacobrblocker** [ChristopheJacquet/PiFmRds#116]
I am using an audio card to stream my music from light show, But every few hours it stops playing the music. It will keep the RDS up though. 

overrun!!! (at least 1.325 ms long) overrun!!! (at least 0.186 ms long) overrun!!! (at least 1.308 ms long) overrun!!! (at least 2.600 ms long) overrun!!! (at least 0.096 ms long) overrun!!! (at least 0.482 ms long) overrun!!! (at least 108.760 ms long) overrun!!! (at least 1.257 ms long) 
Could not rewind in audio file, terminating Terminating: cleanly deactivated the DMA engine and killed the carrier.

Any idea whats making this happen?

**Comment by ChristopheJacquet** [comment]
That's most likely a problem in the program piping a sound stream into Pi-FM-RDS, not a problem with Pi-FM-RDS itself.
