### ISSUE TITLE
WAV Plays in Slow Motion

### ISSUE THREAD

**Issue by mcgregol** [ChristopheJacquet/PiFmRds#123]
Whenever I run it it works but it is in slow mo.  Does anybody know how to fix it?

**Comment by Fanny1203** [comment]
Hello, I have the same problem.
Thank you for sharing this great project!

**Comment by xbh** [comment]
Try tunning the ppm tp10000000

**Comment by mcgregol** [comment]
@xbh Ok, sounds good.

**Comment by Fanny1203** [comment]
Thank you! Actually, it worked fine without changing the parameter today.

**Comment by preetjdp** [comment]
Thanks that worked

> Try tunning the ppm to10000000

**Comment by ChristopheJacquet** [comment]
You shouldn't have to tinker with frequency correction. Marking as a duplicate of #75. Please comment there with your setup (distribution, potential usage of a GUI).

**Comment by ChristopheJacquet** [comment]
You shouldn't have to tinker with frequency correction. Marking as a duplicate of #75. Please comment there with your setup (distribution, potential usage of a GUI).

**Comment by ChristopheJacquet** [comment]
You shouldn't have to tinker with frequency correction. Marking as a duplicate of #75. Please comment there with your setup (distribution, potential usage of a GUI).

**Comment by ChristopheJacquet** [comment]
I found a recommendation to add gpu_freq=250 to /boot/config.txt on the RPi3. Source and explanations: https://github.com/SaucySoliton/PiFmRds/commit/41c6523fc65894a25efa3e1b8d921201679da7ca

Does this work for you?

**Comment by Petrkiller2** [comment]
> Try tunning the ppm to10000000

A milion (1000000) worked instead of 10 milion.
I have RPI 3B+.
