### ISSUE TITLE
Réussir à diffuser l'audio d'un site internet 

### ISSUE THREAD

**Issue by Spyro37** [ChristopheJacquet/PiFmRds#124]
Bonjour, j'ai eu très envie d'utiliser votre programme. 

Car sur le site de raspbian france dans l'article expliquant l'installation et l'utilisation du programme, il est marqué qu'on peut (en changeant à notre sauce ) diffusé l'audio d'un site web. 

Mais je suis très nul en programmation et je ne trouve rien sur internet a ce propos.

Donc je me dirige ici pour avoir de l'aide sur mon problème. 

Merci

**Comment by hxxr** [comment]
Vous pouvez le faire comme ça:
sox -t mp3 http://www.linuxvoice.com/episodes/lv_s02e01.mp3 -t wav -  | sudo ./pi_fm_rds -audio -
(remplacer "http://www.linuxvoice.com/episodes/lv_s02e01.mp3" avec votre adresse internet)

Voir ici:
https://github.com/ChristopheJacquet/PiFmRds#piping-audio-into-pi-fm-rds
