### ISSUE TITLE
PiFMRDs on BananaPi?

### ISSUE THREAD

**Issue by Knogle** [ChristopheJacquet/PiFmRds#144]
Ahoy friends.
Currently i'm looking for a way to get this package running on my Banana Pi M2+ (because i got  a lot of them), and i would like to make some research.
But does someone know if it's possible? Or does it require a lot of work?

**Comment by ChristopheJacquet** [comment]
Maybe, but as far as I can see, the Banana Pi uses a different SoC, so different I/O peripherals. So if it is possible, it will likely require a thorough reimplementation of the modulation code...

Did you make any progress on this?
