### ISSUE TITLE
Possible to go down to 45Mhz?

### ISSUE THREAD

**Issue by danielmoore123** [ChristopheJacquet/PiFmRds#146]
I am wanting to test RDS pass-through on a dummy load at 48.3MhZ for a studio link, this is the only Pi project I can find that can generate a decent RDS signal, are you able to assist how this program can be forced to go that low?
Kind Regards

**Comment by tst403** [comment]
Yes just do the following in **src/pi_fm_rds.c**

Replace this:

            if(carrier_freq < 76e6 || carrier_freq > 108e6)
            fatal("Incorrect frequency specification. Must be in megahertz, of the form 107.9, between 76 and 108.\n");

With those lines:

            if(carrier_freq < 1e6 || carrier_freq > 108e6)
            fatal("Incorrect frequency specification. Must be in megahertz, of the form 107.9, between 1 and 108.\n");

**Comment by ChristopheJacquet** [comment]
I assume the above comment answered the question, so closing.
