### ISSUE TITLE
Another bandwidth?

### ISSUE THREAD

**Issue by Dakurtz422** [ChristopheJacquet/PiFmRds#148]
Hi, I changed minimum allowed frequency in your code, to support my walkie talkie, but I would like to ask where I could change the bandwidth of waves? I was using another radio project and there was a option to change bandwidth with "-b <number>" in command, I dont see anything like that here, So I would like to ask for the place inside of the code; I need something about 21500 kHz

**Comment by ChristopheJacquet** [comment]
PiFmRds is specifically designed for Wideband FM, specifically to demonstrate RDS. There would be no much point changing the bandwidth.

However there are other programs that can produce many kinds of modulation on the RaspberryPi, including NBFM. You can check out https://github.com/F5OEO/rpitx (it even includes PiFmRds!)
