### ISSUE TITLE
Increase the Hertz rate

### ISSUE THREAD

**Issue by pramathk** [ChristopheJacquet/PiFmRds#155]
Please could you increase the hertz rate? the songs playing from the PiFmRds is like 1990 song. If you could some how increase the rate it would be better

**Comment by ChristopheJacquet** [comment]
I'm not sure what the problem is. Is the sound playing too slow? Then this would be the problem investigated in #159.

**Comment by ChristopheJacquet** [comment]
Duplicate of #159

**Comment by ChristopheJacquet** [comment]
Duplicate of #159
