### ISSUE TITLE
(question) Why is PiFmRds stuck in 76 to 109 MHz?

### ISSUE THREAD

**Issue by Ben1701A** [ChristopheJacquet/PiFmRds#160]
And how come when I disable that limiter, the transmission blanks out below 76 or above 109 MHz?

**Comment by bastianorts** [comment]
pifmrds is stuck in this range because this is the range that pretty much every fm receiver use i think thats why there should be no need to go above or below

**Comment by Ben1701A** [comment]
> pifmrds is stuck in this range because this is the range that pretty much every fm receiver use i think thats why there should be no need to go above or below

True...I was wondering about getting past that limit since rpitx for the pi4 isn't stable yet (GPU weirdness when I try anything other than `tune`).
I got an alternative past this, though, so I think I'm good here. Thanks for replying. o>o
