### ISSUE TITLE
Sound stop after few seconds

### ISSUE THREAD

**Issue by manubay** [ChristopheJacquet/PiFmRds#161]
sudo ./pi_fm_rds -audio sound.wav 
It works only 3 or 4 seconds . 
Same problem whith this command: sox -t mp3 http://www.linuxvoice.com/episodes/lv_s02e01.mp3 -t wav -  | sudo ./pi_fm_rds -audio -
Any help?

**Comment by Leo-Aqua** [comment]
Try 
```sudo rmmod w1-gpio```
It works for me.

**Comment by ChristopheJacquet** [comment]
I can't reproduce it on the latest Raspbian. As suggested above, the output pin might be claimed by another program or driver.
