### ISSUE TITLE
my pi4b run on 77mhz,but receive on 77mhz and 97mhz

### ISSUE THREAD

**Issue by zhuzhengren** [ChristopheJacquet/PiFmRds#169]

**Comment by zhuzhengren** [comment]
run on 87mhz,but receive on 87mhz and 108mhz

**Comment by andimik** [comment]
Could you please edit either the text in the subject or in the body?

**Comment by bastianorts** [comment]
the signal is dirty and need filters otherwise you will get harmonics

**Comment by ChristopheJacquet** [comment]
Like [bastianorts](https://github.com/bastianorts) said, it's an expected side effect of generating FM with a PWM.
