### ISSUE TITLE
How do you play .mp3 files from ICECAST?

### ISSUE THREAD

**Issue by ryanginnelly252** [ChristopheJacquet/PiFmRds#174]
Hi, I'm new to this and I'm wondering how do I play http://edge.audioxi.com/CLASSIC on PiFmRds on 92.4 with PS name CLS HITS?

I'm very confused, could anyone help?

**Comment by ryanginn** [comment]
Try:
```
sox -t mp3 http://link-to-icecast-instance.tld/radio.mp3 -t wav -  | sudo ./pi_fm_rds -ps ICECAST -rt Icecast test -audio -
```
It should do the trick!

**Comment by ryanginnelly252** [comment]
Worked.
