### ISSUE TITLE
Can I stream RDS to external FM+RDS transmitter?

### ISSUE THREAD

**Issue by EscapedM** [ChristopheJacquet/PiFmRds#179]
Want to try project w/ FM transmitter by connecting pi via BNC RDS in (50 Ohm or 10 kOhm). Will it work or maybe I need to modify smth?
Or simply, can it be used as RDS coder with external transmitter?

**Comment by ChristopheJacquet** [comment]
It won't work if your FM transmitter is expecting a baseband signal. The signal output by the Raspberry Pi is already frequency-modulated.

You could use Pi-FM-RDS as the basis of a program that would output a baseband signal on a 192 kHz-capable soundcard, whose output you would feed into an FM transmitter. But that's a relatively different project...
