### ISSUE TITLE
Seems not to kill carrier-frequency on exit

### ISSUE THREAD

**Issue by cwshueba** [ChristopheJacquet/PiFmRds#18]
I have an issue with a freshly (today) installed version on my raspberry pi.
When I end the transmission (with ctrl+c) the carrier signal still seems to be broadcasted as the noise (which is normally coming from my radio on the specified frequency) does not come back.
I am able to restart a transmission on a different frequency, so that the "noise" on the first frequency comes back. Unfortunately I have the problem on the new frequency then.

The only way to stop broadcasting is to reboot the raspberry.

I have testet pifrmrds some month ago and didn't have this problem.

What can I do? Is this a bug?

Raspbian GNU/Linux 7
PiFmRds from github 2014-12-05

Thank you!

**Comment by Hatagashira** [comment]
I made a workaround. Put this at the top of the main method in pi_fm_rds.c:

```
atexit(kill_fm);
```

Put all of this above the main method (or at the top of the file, doesnt matter)

```
#define BCM2708_PERI_BASE        0x20000000
//#define GPIO_BASE                (BCM2708_PERI_BASE + 0x200000) /* GPIO controller */
#define INP_GPIO(g) *(gpio+((g)/10)) &= ~(7<<(((g)%10)*3))
#define OUT_GPIO(g) *(gpio+((g)/10)) |=  (1<<(((g)%10)*3))
#define GPIO_SET *(gpio+7)  // sets   bits which are 1 ignores bits which are 0

//#define PAGE_SIZE (4*1024)
#define BLOCK_SIZE (4*1024)

int  mem_fd;
void *gpio_map;
// I/O access
volatile unsigned *gpio;

void setup_io()
{
   /* open /dev/mem */
   if ((mem_fd = open("/dev/mem", O_RDWR|O_SYNC) ) < 0) {
      printf("can't open /dev/mem \n");
      exit(-1);
   }

   /* mmap GPIO */
   gpio_map = mmap(
      NULL,             //Any adddress in our space will do
      BLOCK_SIZE,       //Map length
      PROT_READ|PROT_WRITE,// Enable reading & writting to mapped memory
      MAP_SHARED,       //Shared with other processes
      mem_fd,           //File to map
      GPIO_BASE         //Offset to GPIO peripheral
   );

   close(mem_fd); //No need to keep mem_fd open after mmap

   if (gpio_map == MAP_FAILED) {
      printf("mmap error %d\n", (int)gpio_map);//errno also set!
      exit(-1);
   }

   // Always use volatile pointer!
   gpio = (volatile unsigned *)gpio_map;


} // setup_io

void kill_fm(){
    setup_io();
    INP_GPIO(4); // must use INP_GPIO before we can use OUT_GPIO
    OUT_GPIO(4);
    GPIO_SET = 1<<4;
    printf("FM Transmission terminated.\n");
}
```

If you're really fancy you can make it configurable by commandline argument, but i'm lazy!

**Comment by vallettea** [comment]
Same problem here. Thanks @Hatagashira for the patch

**Comment by mdvanes** [comment]
+1

**Comment by ChristopheJacquet** [comment]
Thanks for the reports, it was a bug! Hatagashira, thanks for your proposal, which helped, but I ended up adding a simpler fix, even though similar. Should be fixed now.

**Comment by Hatagashira** [comment]
Thanks @ChristopheJacquet ! Very elegant solution.
