### ISSUE TITLE
just blocking

### ISSUE THREAD

**Issue by ppoojohn** [ChristopheJacquet/PiFmRds#181]
ok when i broadcast all it does is block the nearby radio staions for a 4 feet radis and the beep every half min to 1 min

**Comment by ryanginn** [comment]
Have you tried installing a filter that blocks harmonics and spurs?

That might resolve that issue.

**Comment by ChristopheJacquet** [comment]
I'm not too surprised given the level of harmonics. That's a known limitation of FM generation using a PWM.
