### ISSUE TITLE
Doesn't compile!

### ISSUE THREAD

**Issue by StefCoders** [ChristopheJacquet/PiFmRds#183]
rm -f *.o
gcc -Wall -std=gnu99 -c -g -march=armv7-a -O3 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -DRASPI=2 rds.c
rds.c: In function ‘set_rds_rt’:
rds.c:240:5: warning: ‘strncpy’ specified bound 64 equals destination size [-Wstringop-truncation]
  240 |     strncpy(rds_params.rt, rt, 64);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rds.c: In function ‘set_rds_ps’:
rds.c:247:5: warning: ‘strncpy’ specified bound 8 equals destination size [-Wstringop-truncation]
  247 |     strncpy(rds_params.ps, ps, 8);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -Wall -std=gnu99 -c -g -march=armv7-a -O3 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -DRASPI=2 waveforms.c
gcc -Wall -std=gnu99 -c -g -march=armv7-a -O3 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -DRASPI=2 pi_fm_rds.c
gcc -Wall -std=gnu99 -c -g -march=armv7-a -O3 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -DRASPI=2 fm_mpx.c
gcc -Wall -std=gnu99 -c -g -march=armv7-a -O3 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -DRASPI=2 control_pipe.c
gcc -Wall -std=gnu99 -c -g -march=armv7-a -O3 -mtune=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -ffast-math -DRASPI=2 mailbox.c
gcc -o pi_fm_rds rds.o waveforms.o mailbox.o pi_fm_rds.o fm_mpx.o control_pipe.o -lm -lsndfile
gcc: fatal error: cannot execute ‘/usr/lib/gcc/arm-linux-gnueabihf/10/collect2’: execv: Exec format error
compilation terminated.
make: *** [Makefile:34: app] Error 1

Any advice will be appreciated!

**Comment by thiagohrm** [comment]
here i was able to compile and use with Raspbian OS **32Bit** with Rasp 3B+

**Comment by ryanginn** [comment]
Sorry for the late reply, however running it as root does the trick.

Let me know if anything happens, cheers!

**Comment by ChristopheJacquet** [comment]
I cannot reproduce this. Based on the error message (`/usr/lib/gcc/arm-linux-gnueabihf/10/collect2`), it looks like there's a problem with your build toolchain. Try out with a fresh Raspbian install, it should work.
