### ISSUE TITLE
While compiling I get this soxr.h missing

### ISSUE THREAD

**Issue by christooss** [ChristopheJacquet/PiFmRds#186]
This is the error when running make:
```
hfm_mpx.c:13:10: fatal error: soxr.h: No such file or directory
   13 | #include <soxr.h>
      |          ^~~~~~~~
compilation terminated.
```
I've tried installing sox libsox-dev libsox-fmt-all.

Any help would be appreciated!

**Comment by ChristopheJacquet** [comment]
You're likely referring to another project (a fork?). PiFmRds doesn't have an `hfm_mpx.c` source file nor does it use soxr.
