### ISSUE TITLE
Mp3 to Wav converter 

### ISSUE THREAD

**Issue by threee3k** [ChristopheJacquet/PiFmRds#192]
Simple python code to convert mp3 files to wav files without going to ad filled sites
Here's the code, make sure to install pydub

from pydub import AudioSegment
sound = AudioSegment.from_mp3("/path/to/file.mp3")
sound.export("file.wav", format="wav")

make sure to change the path

**Comment by ChristopheJacquet** [comment]
You don't need to convert MP3 files to WAV prior to using them with PiFmRds. Thanks to the sndfile library, PiFmRds can read MP3s.
