### ISSUE TITLE
Consider using a socket connection

### ISSUE THREAD

**Issue by oncletom** [ChristopheJacquet/PiFmRds#22]
Hello,

like other folks around, we use the `mpd` backend to manage the playlist queue.
I wonder if there is a way to keep the PiFmRds process always active, and to swap the piped in audio stream?

I wonder if having PiFmRds listening to data on a socket, and another program to swap the content sent to that socket would do the trick.

It would enable more complex pipelines while keeping PiFmRds approach similarly solid.

**Comment by el3ctrician** [comment]
Hi I am a noob in linux but trying to learn anyway if i got it write it will also allow to pause/play and do everything with the program am I right ?
