### ISSUE TITLE
Is there a way to use PiFmRds as non-sudo user ?

### ISSUE THREAD

**Issue by vallettea** [ChristopheJacquet/PiFmRds#25]
the title seems to contain everything...

**Comment by ChristopheJacquet** [comment]
No, sorry. The program needs to write /dev/mem, which only root can do.

Theoretically you could turn the modulation part into a kernel module, with a clean interface to access it from userspace, but in my opinion there is no point doing so: PiFmRds is an **experimental** program, to be tested in very restricted conditions, and it must remain so.

**Comment by creeper6530** [comment]
Why does it need to write into `/dev/mem`? Isn't that a giant security risk?
