### ISSUE TITLE
Broadcast Computer's Audio

### ISSUE THREAD

**Issue by jamesmstone** [ChristopheJacquet/PiFmRds#34]
Hi 
I was wondering if it's possible to broadcast the computer's audio over fm radio  / how would it be done? 
by computer's audio I mean what would be playing out of the speakers?
Thanks heaps
James

**Comment by SandPox** [comment]
no, only can if you setup a stream server on your computer and grab sound via LAN like 
sox -t mp3 http://www.linuxvoice.com/episodes/lv_s02e01.mp3 -t wav -  | sudo ./pi_fm_rds -audio -

**Comment by jamesmstone** [comment]
Ahh ok, thanks for the help :)

**Comment by ChristopheJacquet** [comment]
Closing, outside of the scope of PiFmRds, which is for experimentation only, and not intended as a broadcast *tool*.

**Comment by allegfede** [comment]
by the way. remember to add sox mp3 support with:
sudo apt-get install libsox-fmt-mp3
