### ISSUE TITLE
SOX Error

### ISSUE THREAD

**Issue by danielmoore123** [ChristopheJacquet/PiFmRds#36]
Hi, 
When I use this, I get an error when using Sox, I get:
sudo: sox: command not found 
Error: could not open stdin for audio input.
Terminating: cleanly deactivated the DMA engine.
What does this mean? I am using the code provided and have not done anything that is not in the instructions.
Many Thanks in advance.

**Comment by codeskyblue** [comment]
It is clearly that you need to install sox.
