### ISSUE TITLE
RDS CT PTY and pre-emphasis

### ISSUE THREAD

**Issue by peppi001** [ChristopheJacquet/PiFmRds#4]
Hi!

PiFmRDS is a great project.
What I miss: pre-emphasis and RDS functions (CT, PTY).
It would be good if they can be included in future versions of these.

Many thanks to dev !

PS: Sorry my pour english.

**Comment by undertuga** [comment]
PTY would be really interesting!!
Awesome project!

**Comment by ChristopheJacquet** [comment]
Closing this bug as CT is fixed and pre-emphasis is now tracked by bug #52.
