### ISSUE TITLE
cutoff at 12000.0 Hz

### ISSUE THREAD

**Issue by peppi001** [ChristopheJacquet/PiFmRds#40]
Why 12kHz the cutoff frequency?

Thanks.
Peppi

**Comment by ChristopheJacquet** [comment]
The [spec of FM radio](https://en.wikipedia.org/wiki/FM_broadcasting) states that audio must be limited to 15 kHz. The 80% factor is empirical if I remember correctly; it accounts for the [roll-off](https://en.wikipedia.org/wiki/Roll-off) of the filter.
