### ISSUE TITLE
use of a SDR chipset to avoid noise of the GPIO output

### ISSUE THREAD

**Issue by allegfede** [ChristopheJacquet/PiFmRds#43]
hello.
I'm experimenting with this code, transmitting Stereo audio and RDS over the GPIO, but the result was not so exciting.

I was wondering ... why do not use a SDR chipset over usb bus to transmit audio on the air?
RTL2832U could be a nice candidate ..... any chance to add SDR support to PiFMRds?

Thanks,

Federico

**Comment by ChristopheJacquet** [comment]
Hi Frederico,

That's a totally different project ;-) Granted, part of the code could possibly be reused, but that's totally out of the scope of PiFmRds... Feel free to reuse all PiFmRds' code you want (under the terms of the GPLv3) if you want to start such a project.

BTW, as far as I know, the RTL28233U is a receiver chip, not a transmitter.
