### ISSUE TITLE
Could not get audio to input

### ISSUE THREAD

**Issue by 12458** [ChristopheJacquet/PiFmRds#45]
Error Dump:
Using mbox device /dev/vcio.
Allocating physical memory: size = 3403776     mem_ref = 3     bus_addr = fe625000     virt_addr = 0x7690f000
ppm corr is 0.0000, divider is 1096.4912 (1096 + 2012*2^-12) [nominal 1096.4912].
Error: could not open stdin for audio input.
Terminating: cleanly deactivated the DMA engine and killed the carrier.

**Comment by Cerberus98** [comment]
Try a WAV file, or merging https://github.com/ChristopheJacquet/PiFmRds/pull/23 into your clone and recompiling, then using something like LAME to decode the file on the fly. The current code fails because it attempts to seek on a pipe (to grab the header and other meta about the audio), which is an illegal operation. The error raised is a generic catchall

**Comment by 12458** [comment]
Ok i will apply the patch. Thanks

**Comment by 12458** [comment]
How do I merge #23

**Comment by Cerberus98** [comment]
The normal process is this:

// if you haven't cloned yet:
git clone https://github.com/ChristopheJacquet/PiFmRds.git

git remote add <some name you can type easily> https://github.com/Hatagashira/PiFmRds.git
git fetch --all
git merge <that same name>/patch-1

However, the branch says it has conflicts. All you really care about from that patch are the "raw" mode changes he made. 

I made that change in my repo a month back if you'd like to grab that instead: https://github.com/cerberus98/PiFmRds

Be warned I've been messing with the modulation math and I haven't really tested it out yet.

**Comment by 12458** [comment]
What does conflicts mean

**Comment by Cerberus98** [comment]
It means that there are changes on lines in the patch that were also changed in the repository and git isn't sure which changes to keep, so it's asking the patch implementer to decide.

**Comment by LiuChiennan** [comment]
hello, when I use the pipe, I met the same problem, how to solve it ?please!
