### ISSUE TITLE
Pipe all RPi2 audio to PiFmRds?

### ISSUE THREAD

**Issue by mitchellurgero** [ChristopheJacquet/PiFmRds#46]
Trying to pipe all audio that would output on HDMI or Composit through to PiFMRds, how would one go about doing this? Looking to setup a daemon to run in the background with kodi so I can listen to music and such through my home stereo wirelessly.

Thanks!

**Comment by Blenderpics** [comment]
Take a look at [this issue](https://github.com/ChristopheJacquet/PiFmRds/issues/44).
although by using the method i described there you would have no audio out of HDMI/jack anymore.
If you want to still output the audio via HDMI while passing it to PiFm, you could use audio routes in .asoundrc, but i havn't tried it my self so far
