### ISSUE TITLE
Interference

### ISSUE THREAD

**Issue by danielmoore123** [ChristopheJacquet/PiFmRds#51]
Just a question, what harmonics does this let out? Does this program let out anything else other than the MhZ FM signal? 
Is there anyway to filter what does come out?
Regards

**Comment by DF9TS** [comment]
By nature of generating the signal with the IO Pin - which is effectively an ON/OFF switch - the program lets out all sorts of unwanted spectrum.

Just put a filter in. For the filter to work ok it needs to be roughly matched. If you do not understand this statement please look out for the closest ham radio (amateur radio) club in your area. I am sure you will find someone to help you practically. 

If you want to do it yourself: Get an SDR receiver (preferably the AMSAT-UK Funcube Dongle Pro http://amsat-uk.org/funcube/funcube-dongle-sdr/ ) and you can watch the spectrum on a 2nd laptop/PC

BR

Gerd.
