### ISSUE TITLE
Noob question about harmonics

### ISSUE THREAD

**Issue by tgeorgiop** [ChristopheJacquet/PiFmRds#57]
Hello. As far as I understand harmonics are created because of the square waves that raspberry produce. What if we use dac in the output?

**Comment by Miegl** [comment]
You will need some kund of band-pass filter

**Comment by itdaniher** [comment]
tgeorgiop - the DAC isn't fast enough, if I recall correctly, and in any case you'll need filtering before you get something you want to put on air.
