### ISSUE TITLE
Noob issues with Getting rds to work

### ISSUE THREAD

**Issue by Hellcat1212** [ChristopheJacquet/PiFmRds#61]
Im pretty new to radio on any device, so getting the pi to transmit is quite hard work. I have installed everything correctly, yet when broadcasting it, no text appears what so ever on my radio or on my phone. I thought it wa my rx fault but then i realised it showed up other radio stations ps names.
If anyone could help that would be great.

ps (i know im a noob and i dont know what im talking about. I have had other experience on the raspberry pi though so plz dont be patronising

**Comment by danielmoore123** [comment]
What code are you running? If you share this we can show you how to get the text. There are 2 text elements, the static 8 character PS name and the Long scrolling "radiotext", assuming your code looks like this:
`-freq 100.0 -audio sound.wav`
Just add these bits somewhere, the order is not important:
`-ps "Cool FM" -rt "This is the coolest station" `
That should do it!
