### ISSUE TITLE
Stereo doesnt work properly on RPi Zero

### ISSUE THREAD

**Issue by hex007** [ChristopheJacquet/PiFmRds#62]
I tried the program and used the stereo wav 44100 file. Both channels are mixed. Is there a stereo parameter to be passed?

**Comment by ChristopheJacquet** [comment]
What does Pi-FM-RDS print out? "1 channel, monophonic operation" or "generating stereo multiplex"?

**Comment by hex007** [comment]
The issue was two years ago, I will just close it now
