### ISSUE TITLE
Could not open stdin for audio input

### ISSUE THREAD

**Issue by Smarticles101** [ChristopheJacquet/PiFmRds#66]
I try running this command:
avconv -i "./pirateradio/music/00 - to the sky.mp3" -f s16le - | sudo ./PiFmRds/src/pi_fm_rds -audio - -freq 88.8

and then i get this output:
Input #0, mp3, from './pirateradio/music/00 - to the sky.mp3':
  Metadata:
    title           : to the sky
    artist          : owl city
    album_artist    : owl city
    TYER            : 0
    track           : 0/0
    disc            : 0/0
  Duration: 00:03:39.14, start: 0.000000, bitrate: 256 kb/s
    Stream #0.0: Audio: mp3, 44100 Hz, 2 channels, s16p, 256 kb/s
Output #0, s16le, to 'pipe:':
  Metadata:
    title           : to the sky
    artist          : owl city
    album_artist    : owl city
    TYER            : 0
    track           : 0/0
    disc            : 0/0
    encoder         : Lavf56.1.0
    Stream #0.0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      encoder         : Lavc56.1.0 pcm_s16le
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (native) -> pcm_s16le (native))
Press ctrl-c to stop encoding
Input stream #0:0 frame changed from rate:44100 fmt:s16p ch:2 chl:stereo to rate:44100 fmt:s16 ch:2 chl:stereo
Error: could not open stdin for audio input.
Terminating: cleanly deactivated the DMA engine and killed the carrier.

**Comment by hxxr** [comment]
#45
