### ISSUE TITLE
make: *** [clean] Error 1

### ISSUE THREAD

**Issue by jethroweb** [ChristopheJacquet/PiFmRds#69]
Bonjour,
Lors de l'installation de PiFmRds sur mon Raspberry Pi 3, avec la commande "make clean" j'obtiens l'erreur suivante : 

```
pi@raspberrypi:~/PiFmRds/src $ make clean
rm *.o
rm: impossible de supprimer « *.o »: Aucun fichier ou dossier de ce type
Makefile:51: recipe for target 'clean' failed
make: *** [clean] Error 1
```

Si je saute cette étape, ça fonctionne. Mais est-ce qu'il y a une solution à l'erreur que j'obtiens ?

**Comment by ChristopheJacquet** [comment]
Il n'y avait absolument rien de grave. Comme c'était la première fois que vous le compiliez, il n'y avait rien à nettoyer...

J'ai modifié le Makefile pour qu'il n'y ait plus cette erreur à l'avenir.
