### ISSUE TITLE
Make it compatible with OrangePI

### ISSUE THREAD

**Issue by kiki67100** [ChristopheJacquet/PiFmRds#71]
Hello,

I would to know if possible and/or you can do your PiFmRds compatible with OrangePI One ( H3 AllWinner processor ) ?

Regards

**Comment by ChristopheJacquet** [comment]
It's probably not easy to do. To output frequency-modulated VHF signals, the original pifm and PiFmRds use a hardware hack in the Raspberry Pi's Broadcom SoC. The OrangePi uses a different SoC from a different manufacturer. So 1) I'm not sure a similar hack is possible on this hardware, 2) the frequency-modulation code would probably be substantially different, so it's a whole new project !

Note however that the part of the code that generates the FM multiplex and RDS subcarrier is totally portable, you can even run it on a PC and write output to a WAV file.

So closing this bug for now as it's out of the scope of PiFmRds. Of course I'll reconsider if someone comes with a patch with VHF generation on another board :)
