### ISSUE TITLE
signal strength

### ISSUE THREAD

**Issue by roizcorp** [ChristopheJacquet/PiFmRds#77]
I've managed to make it operable, I use 20cm antena. The problem is that I cannot get a "clean" frequency so I always get some "noise" while listening via radio.

Is there a way to increase the signal strength (amp up the power or something?)

**Comment by tadKeys** [comment]
Maybe try this implementation:
https://github.com/SaucySoliton/PiFmRds

**Comment by roizcorp** [comment]
yes! sounds better!
