### ISSUE TITLE
Getting the most out of your pi

### ISSUE THREAD

**Issue by Niall7459** [ChristopheJacquet/PiFmRds#78]
I assume that there is specific settings for getting the best transmission range and quality.

For example

87.5 Mhz = Long distance/worse quality
160 Mhz = Shorter distance/better quality

Am i correct?

Also how can I make the optinum antenna?

**Comment by Miegl** [comment]
Well, the FM band is only like 87Mhz - 108Mhz, so don't even bother whats "better", just find some blank spot and use that.
As a antenna you can use a piece of wire - not very effective but works. Im sure you will find some FM antenna guides on the internet.
To get the optimal length of the wire use some formula like this: `75 / FREQ`
So if my desired frequency is 98Mhz, my wire will be `75/98` = 0.765 cm.

But for better audio quality you will need improvments on the software side. I will maybe make a fork with my own patches.
