### ISSUE TITLE
USB Antenna

### ISSUE THREAD

**Issue by Oscaretto** [ChristopheJacquet/PiFmRds#80]
Hi, can i use an USB antenna ?
Es. http://m.gearbest.com/tv-box-mini-pc/pp_188369.html

**Comment by Miegl** [comment]
Of course this won't work, firstly its DVB-T reciever, not antenna, secondly it's possible to output signal only using GPIO.

**Comment by Oscaretto** [comment]
The gpio is very low signal

**Comment by Miegl** [comment]
Well its a hack, not professional FM transmitter meant to be used in production.
Also don't forget that you can boost the signal with high gain antenna. And of course you can use some amplifier circuit, but keep in mind that using amplifier together with Raspberry Pi probably isn't good idea.

**Comment by Oscaretto** [comment]
Why ins't a good idea?
