### ISSUE TITLE
infinite loop for the same song

### ISSUE THREAD

**Issue by tchiobtcha** [ChristopheJacquet/PiFmRds#84]
hi
i want to automate the reading of all songs but the problem th pifm keep repeating the same song
is there any thing to change from the c code to make it stop after finshing the song ?

**Comment by Miegl** [comment]
Just pipe the stuff that you wanna play using something like sox.

**Comment by MinePro120** [comment]
What i did, was to make a huge .wav file (10 hours) with all the songs I wanted in it, and made it repeat it. That was the only solution for me as I don't know how to program and make something like a schedule.

**Comment by Miegl** [comment]
I highly recommend LibreTime (fork of AirTime).

**Comment by ChristopheJacquet** [comment]
It is not currently supported. See #82 for this feature request.
