### ISSUE TITLE
How to generate waveforms for another subcarrier

### ISSUE THREAD

**Issue by miegl** [ChristopheJacquet/PiFmRds#85]
Hi,
I would like to know how to generate waveforms array for subcarrier (for example 67 khz)

In the project there is already waveforms array for 38 khz and 19 khz, but I would like to know how to generate these.

Thanks

**Comment by ChristopheJacquet** [comment]
Pi-FM-RDS samples the MPX data at 228 kHz. So 57, 38 and 19 kHz are very easy to generate as the sine waves are always aligned with the sampling frequency (respectively 1/4, 1/6, 1/12). So the samples are pre-computed (here: https://github.com/ChristopheJacquet/PiFmRds/blob/3f8ebae11d72cf3d1b4678a5b993ba03abc03d2e/src/fm_mpx.c#L48). For non-aligned subcarriers you will have to compute the samples (use sin() namely), but this sounds doable.
