### ISSUE TITLE
no such command

### ISSUE THREAD

**Issue by TechDark** [ChristopheJacquet/PiFmRds#90]
when i type in 

sudo ./pi_fm_rds -audio "lofi30.wav"  -freq 87.50 -ps "KlugZigg"

it says    "sudo: ./pi_fm_rds:command not found"
what is the problem?

**Comment by GoodOldJack12** [comment]
are you in the src directory?

**Comment by ChristopheJacquet** [comment]
Did you build the program? (run make)
