### ISSUE TITLE
How do I play a folder using Sox?

### ISSUE THREAD

**Issue by patrickdemers6** [ChristopheJacquet/PiFmRds#92]
As the title says, how do I play the audio files in a folder using Sox? Thanks

**Comment by thedarkeye** [comment]
You can use `sox /path/to/folder/* -t wav - | sudo ./pi_fm_rds -freq 107.9 -audio -`

**Comment by patrickdemers6** [comment]
Is there a way to make the order random? Thanks

**Comment by thedarkeye** [comment]
I don't think there's an option available for that. But you can try something with `find /path/to/folder -type f | sort -R`

**Comment by ChristopheJacquet** [comment]
Closing, as it's beyond the scope of PiFmRds (experiment with FM/RDS modulation), and the @thedarkeye provided a partial solution.
