### ISSUE TITLE
Makefile44 error

### ISSUE THREAD

**Issue by d3bugg3d** [ChristopheJacquet/PiFmRds#93]
I keep on getting a Makefile:44: recipe for target 'pi_fm_rds.o' failed
make: *** [pi_fm_rds.o] Error 1.

I'm SSH'ing into my Pi 2 from Putty. Any help?

**Comment by thedarkeye** [comment]
Have you got all the dependencies needed? Like  `libsndfile1-dev`

**Comment by d3bugg3d** [comment]
Yeah I typed that command in on my Pi. Should I retry it? What command do I enter?

**Comment by d3bugg3d** [comment]
Can anybody comment on this? Does this hack still work for other people?

**Comment by thedarkeye** [comment]
I've tested it on my Pi 2 B+ with Raspbian Jessie Lite and it works fine.
I don't know why it wouldn't work for you, if you haven't already try updating with `apt-get update && apt-get upgrade`.

**Comment by d3bugg3d** [comment]
When I try installing the update or whatever it says failed to install.

⁣Sent from Blue ​

**Comment by d3bugg3d** [comment]
https://null-byte.wonderhowto.com/how-to/hack-radio-frequencies-hijacking-fm-radio-with-raspberry-pi-wire-0177007/

Trying to follow this guide. It won't install the libsnd accordingly. I
think I need to start from scratch again. Do you have the proper steps?

**Comment by d3bugg3d** [comment]
I don't know which commands to use to upgrade it or install it or whatever.
Then it says that too much of the disc memory is taken or some shit like
that.

**Comment by ChristopheJacquet** [comment]
I can advise you to start from a fresh Raspbian install to do your experiments with PiFmRds. Then just install libsndfile1-dev (apt-get update && apt-get install libsndfile1-dev) and you should be all set.

Closing this issue as it's not directly related to PiFmRds.

**Comment by d3bugg3d** [comment]
Ok, whenever I type in the git clone
https://github.com/ChristopheJacquet/PiFmRds.git
cd PiFmRds/src
make clean
make

I get an error saying "Makefile:44: recipe for target 'pi_fm_rds.o' failed
make: *** [pi_fm_rds.o] Error 1

On Mon, Aug 21, 2017 at 2:31 PM, ChristopheJacquet <notifications@github.com
