### ISSUE TITLE
Makefile:44 Issue

### ISSUE THREAD

**Issue by ghost** [ChristopheJacquet/PiFmRds#94]
Ok, whenever I type in the git clone
https://github.com/ChristopheJacquet/PiFmRds.git
cd PiFmRds/src
make clean
make

I get an error saying "Makefile:44: recipe for target 'pi_fm_rds.o' failed
make: *** [pi_fm_rds.o] Error 1

**Comment by ChristopheJacquet** [comment]
Do you have GCC installed?
