### ISSUE TITLE
How to calculate offset words ?

### ISSUE THREAD

**Issue by kutlay** [ChristopheJacquet/PiFmRds#95]
Hi,
I'm curious about how the offset words calculated ? RDS message is broken when I change them.

**Comment by ChristopheJacquet** [comment]
Hi,
Offset words are not calculated, but specified in the RDS Standard. They are arbitrary values (which respect some constraints however). They allow the receiver to synchronize on block (and hence group) boundary.

See http://www.nrscstandards.org/documentarchive/NRSC-4%201998.pdf Annex A p. 70.
